name: build-opnwrt-WR720N

on:
  repository_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: Update and upgrade
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y

      - name: Install build dependencies
        run: |
          sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Clone source code
        run: |
          git clone https://github.com/openwrt/archive.git
          cd archive
          git checkout chaos_calmer
          git pull

      - name: Update and install packages
        run: |
          cd archive
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          cd archive
          make download -j$(nproc)
          make -j$(nproc)

      - name: Publish firmware
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: /home/user/openwrt/bin/targets/ath79/generic/*
          asset_name: firmware.zip
          asset_content_type: application/zip

      - name: Clean up
        run: |
          cd archive
          make clean
